
package com.mobivat.mobivat_is.cyclos_payment;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaymentWebService", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaymentWebService {


    /**
     * 
     * @param params
     * @return
     *     returns com.mobivat.mobivat_is.cyclos_payment.PaymentStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "simulatePayment", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.SimulatePayment")
    @ResponseWrapper(localName = "simulatePaymentResponse", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.SimulatePaymentResponse")
    public PaymentStatus simulatePayment(
        @WebParam(name = "params", targetNamespace = "")
        PaymentParameters params);

    /**
     * 
     * @param transferId
     * @return
     *     returns java.util.List<com.mobivat.mobivat_is.cyclos_payment.ChargebackResult>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doBulkChargeback", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.DoBulkChargeback")
    @ResponseWrapper(localName = "doBulkChargebackResponse", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.DoBulkChargebackResponse")
    public List<ChargebackResult> doBulkChargeback(
        @WebParam(name = "transferId", targetNamespace = "")
        List<Long> transferId);

    /**
     * 
     * @param traceNumber
     * @return
     *     returns com.mobivat.mobivat_is.cyclos_payment.ChargebackResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reverse", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.Reverse")
    @ResponseWrapper(localName = "reverseResponse", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.ReverseResponse")
    public ChargebackResult reverse(
        @WebParam(name = "traceNumber", targetNamespace = "")
        String traceNumber);

    /**
     * 
     * @param ticket
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "expireTicket", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.ExpireTicket")
    @ResponseWrapper(localName = "expireTicketResponse", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.ExpireTicketResponse")
    public boolean expireTicket(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket);

    /**
     * 
     * @param params
     * @return
     *     returns com.mobivat.mobivat_is.cyclos_payment.PaymentResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doPayment", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.DoPayment")
    @ResponseWrapper(localName = "doPaymentResponse", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.DoPaymentResponse")
    public PaymentResult doPayment(
        @WebParam(name = "params", targetNamespace = "")
        PaymentParameters params);

    /**
     * 
     * @param traceNumber
     * @return
     *     returns java.util.List<com.mobivat.mobivat_is.cyclos_payment.ChargebackResult>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doBulkReverse", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.DoBulkReverse")
    @ResponseWrapper(localName = "doBulkReverseResponse", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.DoBulkReverseResponse")
    public List<ChargebackResult> doBulkReverse(
        @WebParam(name = "traceNumber", targetNamespace = "")
        List<String> traceNumber);

    /**
     * 
     * @param params
     * @return
     *     returns java.util.List<com.mobivat.mobivat_is.cyclos_payment.PaymentResult>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doBulkPayment", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.DoBulkPayment")
    @ResponseWrapper(localName = "doBulkPaymentResponse", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.DoBulkPaymentResponse")
    public List<PaymentResult> doBulkPayment(
        @WebParam(name = "params", targetNamespace = "")
        List<PaymentParameters> params);

    /**
     * 
     * @param transferId
     * @return
     *     returns com.mobivat.mobivat_is.cyclos_payment.ChargebackResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "chargeback", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.Chargeback")
    @ResponseWrapper(localName = "chargebackResponse", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.ChargebackResponse")
    public ChargebackResult chargeback(
        @WebParam(name = "transferId", targetNamespace = "")
        Long transferId);

    /**
     * 
     * @param params
     * @return
     *     returns com.mobivat.mobivat_is.cyclos_payment.PaymentResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmPayment", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.ConfirmPayment")
    @ResponseWrapper(localName = "confirmPaymentResponse", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.ConfirmPaymentResponse")
    public PaymentResult confirmPayment(
        @WebParam(name = "params", targetNamespace = "")
        ConfirmPaymentParameters params);

    /**
     * 
     * @param params
     * @return
     *     returns com.mobivat.mobivat_is.cyclos_payment.RequestPaymentResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "requestPaymentConfirmation", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.RequestPaymentConfirmation")
    @ResponseWrapper(localName = "requestPaymentConfirmationResponse", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", className = "com.mobivat.mobivat_is.cyclos_payment.RequestPaymentConfirmationResponse")
    public RequestPaymentResult requestPaymentConfirmation(
        @WebParam(name = "params", targetNamespace = "")
        RequestPaymentParameters params);

}
