
package com.mobivat.mobivat_is.cyclos_payment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "payment", targetNamespace = "http://payments.webservices.cyclos.strohalm.nl/", wsdlLocation = "http://dev.mobivat.com/vat/services/payment?wsdl")
public class Payment
    extends Service
{

    private final static URL PAYMENT_WSDL_LOCATION;
    private final static WebServiceException PAYMENT_EXCEPTION;
    private final static QName PAYMENT_QNAME = new QName("http://payments.webservices.cyclos.strohalm.nl/", "payment");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dev.mobivat.com/vat/services/payment?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENT_WSDL_LOCATION = url;
        PAYMENT_EXCEPTION = e;
    }

    public Payment() {
        super(__getWsdlLocation(), PAYMENT_QNAME);
    }

    public Payment(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENT_QNAME, features);
    }

    public Payment(URL wsdlLocation) {
        super(wsdlLocation, PAYMENT_QNAME);
    }

    public Payment(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENT_QNAME, features);
    }

    public Payment(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Payment(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentWebService
     */
    @WebEndpoint(name = "paymentPort")
    public PaymentWebService getPaymentPort() {
        return super.getPort(new QName("http://payments.webservices.cyclos.strohalm.nl/", "paymentPort"), PaymentWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentWebService
     */
    @WebEndpoint(name = "paymentPort")
    public PaymentWebService getPaymentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://payments.webservices.cyclos.strohalm.nl/", "paymentPort"), PaymentWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENT_EXCEPTION!= null) {
            throw PAYMENT_EXCEPTION;
        }
        return PAYMENT_WSDL_LOCATION;
    }

}
